source "http://rubygems.org"
source "http://gemcutter.org/"

gem "adsf"
gem "guard-nanoc"
gem "image_size"
gem "kramdown"
gem "mime-types"
gem "nanoc"
gem "nokogiri"
gem "pygments.rb"
gem "rainpress"
gem "rake"
gem "systemu"
gem "terser"
gem "to_slug"
gem "uglifier"

# Dependency for XML Sitemap generation
gem "builder"
