source "http://rubygems.org"
source "http://gemcutter.org/"
source "http://gems.github.com"

gem "nanoc"
gem "guard-nanoc"
gem "adsf"
gem "kramdown"
gem "nokogiri"
gem "to_slug"
gem "systemu"
gem "mime-types"
gem "uglifier"
gem "rake"
gem "pygments.rb"
gem "image_size"
gem "rainpress"

# Dependency for XML Sitemap generation
gem "builder"
